#!/bin/sh
# ##########################################################################
# ####                                                                  ####
# ####                      RTP Audio Server Project                    ####
# ####                    ============================                  ####
# ####                                                                  ####
# #### Conversion to OGG Format Script                                  ####
# ####                                                                  ####
# ####           Copyright (C) 2011-2012 by Thomas Dreibholz            ####
# ####                                                                  ####
# #### Contact:                                                         ####
# ####    EMail: dreibh@iem.uni-due.de.de                               ####
# ####    WWW:   http://www.iem.uni-due.de.de/~dreibh/rn                ####
# ####                                                                  ####
# #### ---------------------------------------------------------------- ####
# ####                                                                  ####
# #### This program is free software: you can redistribute it and/or    ####
# #### modify it under the terms of the GNU General Public License as   ####
# #### published by the Free Software Foundation, either version 3 of   ####
# #### the License, or (at your option) any later version.              ####
# ####                                                                  ####
# #### This program is distributed in the hope that it will be useful,  ####
# #### but WITHOUT ANY WARRANTY; without even the implied warranty of   ####
# #### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    ####
# #### GNU General Public License for more details.                     ####
# ####                                                                  ####
# #### You should have received a copy of the GNU General Public        ####
# #### License along with this program.  If not, see                    ####
# #### <http://www.gnu.org/licenses/>.                                  ####
# ####                                                                  ####
# ##########################################################################
# $Id$


if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 [Input file] [OGG Output File]"
   exit 1
fi

mpg321 $1 -w - | oggenc -o $2 -
