.\" ##########################################################################
.\" ####                                                                  ####
.\" ####                      RTP Audio Server Project                    ####
.\" ####                    ============================                  ####
.\" ####                                                                  ####
.\" #### RTP Audio Client Manpage                                         ####
.\" ####                                                                  ####
.\" ####           Copyright (C) 1999-2012 by Thomas Dreibholz            ####
.\" ####                                                                  ####
.\" #### Contact:                                                         ####
.\" ####    EMail: dreibh@iem.uni-due.de                                  ####
.\" ####    WWW:   http://www.iem.uni-due.de/~dreibh/rtpaudio             ####
.\" ####                                                                  ####
.\" #### ---------------------------------------------------------------- ####
.\" ####                                                                  ####
.\" #### This program is free software: you can redistribute it and/or    ####
.\" #### modify it under the terms of the GNU General Public License as   ####
.\" #### published by the Free Software Foundation, either version 3 of   ####
.\" #### the License, or (at your option) any later version.              ####
.\" ####                                                                  ####
.\" #### This program is distributed in the hope that it will be useful,  ####
.\" #### but WITHOUT ANY WARRANTY; without even the implied warranty of   ####
.\" #### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    ####
.\" #### GNU General Public License for more details.                     ####
.\" ####                                                                  ####
.\" #### You should have received a copy of the GNU General Public        ####
.\" #### License along with this program.  If not, see                    ####
.\" #### <http://www.gnu.org/licenses/>.                                  ####
.\" ####                                                                  ####
.\" ##########################################################################
.\" $Id$
.\"
.\" ###### Setup ############################################################
.Dd January 2, 2012
.Dt rtpa-vclient 1
.Os rtpa-vclient
.\" ###### Name #############################################################
.Sh NAME
.Nm rtpa-vclient
.Nd RTP Audio Client (stress test version)
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm rtpa-vclient
.Op URL
.Op Fl debug
.Op Fl null
.Op Fl encoding=number
.Op Fl prefix=name
.Op Fl info=infostring
.Op Fl force-ipv4
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm rtpa-vclient
is the RTP Audio stress test client application.
.Pp
.\" ###### Arguments ########################################################
.Sh OPTIONS
The following options may be provided:
.Bl -tag -width indent
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It rtpa-vclient
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
http://www.iem.uni-due.de/~dreibh/rtpaudio
.br
mailto://dreibh@iem.uni-due.de
.br
