.\" ##########################################################################
.\" ####                                                                  ####
.\" ####                      RTP Audio Server Project                    ####
.\" ####                    ============================                  ####
.\" ####                                                                  ####
.\" #### RTP Audio Client Manpage                                         ####
.\" ####                                                                  ####
.\" ####           Copyright (C) 1999-2023 by Thomas Dreibholz            ####
.\" ####                                                                  ####
.\" #### Contact:                                                         ####
.\" ####    EMail: thomas.dreibholz@gmail.com                                  ####
.\" ####    WWW:   https://www.nntb.no/~dreibh/rtpaudio                ####
.\" ####                                                                  ####
.\" #### ---------------------------------------------------------------- ####
.\" ####                                                                  ####
.\" #### This program is free software: you can redistribute it and/or    ####
.\" #### modify it under the terms of the GNU General Public License as   ####
.\" #### published by the Free Software Foundation, either version 3 of   ####
.\" #### the License, or (at your option) any later version.              ####
.\" ####                                                                  ####
.\" #### This program is distributed in the hope that it will be useful,  ####
.\" #### but WITHOUT ANY WARRANTY; without even the implied warranty of   ####
.\" #### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    ####
.\" #### GNU General Public License for more details.                     ####
.\" ####                                                                  ####
.\" #### You should have received a copy of the GNU General Public        ####
.\" #### License along with this program.  If not, see                    ####
.\" #### <http://www.gnu.org/licenses/>.                                  ####
.\" ####                                                                  ####
.\" ##########################################################################
.\" $Id$
.\"
.\" ###### Setup ############################################################
.Dd September 6, 2014
.Dt rtpa-qclient 1
.Os rtpa-qclient
.\" ###### Name #############################################################
.Sh NAME
.Nm rtpa-qclient
.Nd RTP Audio Client (Qt GUI version)
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm rtpa-qclient
.Op Fl url=URL
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm rtpa-qclient
is the RTP Audio client application.
.Pp
.\" ###### Arguments ########################################################
.Sh OPTIONS
The following options may be provided:
.Bl -tag -width indent
.It Fl url=URL
Specifies the URL to use.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It rtpa-qclient -url=rtpa://server.domain/Test1.list
.It rtpa-qclient -url=rtpa+udp://server.domain/Test1.list
.It rtpa-qclient -url=rtpa+sctp://server.domain/Test1.list
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/rtpaudio
.br
mailto://thomas.dreibholz@gmail.com
.br
