.\" ##########################################################################
.\" ####                                                                  ####
.\" ####                      RTP Audio Server Project                    ####
.\" ####                    ============================                  ####
.\" ####                                                                  ####
.\" #### RTP Audio Server Manpage                                         ####
.\" ####                                                                  ####
.\" ####           Copyright (C) 1999-2021 by Thomas Dreibholz            ####
.\" ####                                                                  ####
.\" #### Contact:                                                         ####
.\" ####    EMail: dreibh@iem.uni-due.de                                  ####
.\" ####    WWW:   http://www.iem.uni-due.de.de/~dreibh/rtpaudio          ####
.\" ####                                                                  ####
.\" #### ---------------------------------------------------------------- ####
.\" ####                                                                  ####
.\" #### This program is free software: you can redistribute it and/or    ####
.\" #### modify it under the terms of the GNU General Public License as   ####
.\" #### published by the Free Software Foundation, either version 3 of   ####
.\" #### the License, or (at your option) any later version.              ####
.\" ####                                                                  ####
.\" #### This program is distributed in the hope that it will be useful,  ####
.\" #### but WITHOUT ANY WARRANTY; without even the implied warranty of   ####
.\" #### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    ####
.\" #### GNU General Public License for more details.                     ####
.\" ####                                                                  ####
.\" #### You should have received a copy of the GNU General Public        ####
.\" #### License along with this program.  If not, see                    ####
.\" #### <http://www.gnu.org/licenses/>.                                  ####
.\" ####                                                                  ####
.\" ##########################################################################
.\" $Id$
.\"
.\" ###### Setup ############################################################
.Dd September 6, 2014
.Dt rtpa-server 1
.Os rtpa-server
.\" ###### Name #############################################################
.Sh NAME
.Nm rtpa-server
.Nd RTP Audio Server
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm rtpa-server
.Op Fl port=port
.Op Fl directory=path
.Op Fl timeout=secs
.Op Fl maxpktsize=bytes
.Op Fl disable-qm
.Op Fl enable-qm
.Op Fl disable-ls
.Op Fl enable-ls
.Op Fl force-ipv4
.Op Fl use-ipv6
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm rtpa-server
is the RTP Audio server application.
.Pp
.\" ###### Arguments ########################################################
.Sh OPTIONS
The following options may be provided:
.Bl -tag -width indent
.It Fl port=port
TBD.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It rtpa-server
.It rtpa-server -sctp
.It rtpa-server -directory=/path/to/media/directory
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz
.br
https://www.uni-due.de/~be0001/rtpaudio
.br
mailto://dreibh@iem.uni-due.de
.br
